server:
  port: 8888
spring:
  datasource:
    # 数据源基本配置
    username: dotchat_chuhelan
    password: YezFPcEFrpZ5WKD7
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dotchat.chuhelan.com:3306/dotchat_chuhelan?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
  thymeleaf:
    prefix: classpath:/templates/
mybatis:
  type-aliases-package: com.chuhelan.dotchat.beans #所有Entity别名类所在包
  mapper-locations: [ classpath:mapper/**/*.xml ]
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
